[package]
name = "radcoin"
version = "0.1.0"
authors = ["Dane Larsen <dane.t.larsen@gmail.com>"]

[dependencies]
base64 = "0.9.0"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"
ring = "0.12.1"
untrusted = "0.5.1"
